### ISSUE TITLE
FieldError: Unsupported lookup 'name'

### ISSUE THREAD

**Issue by philippeowagner** [frol/django-quering-jsonfield#2]
Getting 

    Object.objects.filter(object_data__name="blub")
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
        return self._filter_or_exclude(False, *args, **kwargs)
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
        clone.query.add_q(Q(*args, **kwargs))
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1310, in add_q
        clause, require_inner = self._add_q(where_part, self.used_aliases)
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1338, in _add_q
        allow_joins=allow_joins, split_subq=split_subq,
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1209, in build_filter
        condition = self.build_lookup(lookups, col, value)
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1100, in build_lookup
        lhs = self.try_transform(lhs, name, lookups)
      File "/Users/phi/Sandbox/demo/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1118, in try_transform
        (name, lhs.output_field.__class__.__name__))
    FieldError: Unsupported lookup 'name' for JSONQField or join on the field not permitted.

using SQLite and Django 1.8.x

Any ideas or hints?

PS: I renamed `JSONField` to `JSONQField` to avoid conflicts with the other `JSONField`.

**Comment by frol** [comment]
I haven't tested this with Django 1.8, so it might be just incompatible. However, I need to ask whether you have not forgotten to set `JSONAwareManager` in your `Object` model.

P.S. I'm open to pull requests in case the changes are necessary.

**Comment by philippeowagner** [comment]
Will be closed in #3
